// =================================================================
// include/Camus/LlmInteraction.hpp
// =================================================================
// Abstract interface for interacting with LLMs.

#pragma once

#include <string>

namespace Camus {

class LlmInteraction {
public:
    virtual ~LlmInteraction() = default;

    /**
     * @brief Sends a prompt to the LLM and gets a response.
     * @param prompt The fully-formed prompt to send to the model.
     * @return The text generated by the model.
     */
    virtual std::string getCompletion(const std::string& prompt) = 0;
};

} // namespace Camus